#include "riscv-macros.h"

        TEST_RISCV_BEGIN

        li    x2, 2
        mul   x3, x2, x2
        addi  x4, x2, 1
        addi  x5, x2, 1
        addi  x6, x2, 1
        addi  x7, x2, 1
        mul   x3, x2, x2
        addi  x4, x2, 1
        addi  x5, x2, 1
        addi  x6, x2, 1
        addi  x7, x2, 1
        mul   x3, x2, x2
        addi  x4, x2, 1
        addi  x5, x2, 1
        addi  x6, x2, 1
        addi  x7, x2, 1
        mul   x3, x2, x2
        addi  x4, x2, 1
        addi  x5, x2, 1
        addi  x6, x2, 1
        addi  x7, x2, 1
        mul   x3, x2, x2
        addi  x4, x2, 1
        addi  x5, x2, 1
        addi  x6, x2, 1
        addi  x7, x2, 1
        mul   x3, x2, x2
        addi  x4, x2, 1
        addi  x5, x2, 1
        addi  x6, x2, 1
        addi  x7, x2, 1
        mul   x3, x2, x2
        addi  x4, x2, 1
        addi  x5, x2, 1
        addi  x6, x2, 1
        addi  x7, x2, 1
        mul   x3, x2, x2
        addi  x4, x2, 1
        addi  x5, x2, 1
        addi  x6, x2, 1
        addi  x7, x2, 1

        TEST_RISCV_END